// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from xxwire.go:

func InitEndingA(name string) EndingA {
	player := NewPlayer(name)
	monster := NewMonster()
	endingA := NewEndingA(player, monster)
	return endingA
}

func InitEndingB(name string) EndingB {
	player := NewPlayer(name)
	monster := NewMonster()
	endingB := NewEndingB(player, monster)
	return endingB
}
