// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from xxwire.go:

func InitMission(name string) (Mission, func(), error) {
	player, cleanup, err := NewPlayer(name)
	if err != nil {
		return Mission{}, nil, err
	}
	monster := NewMonster()
	mission := NewMission(player, monster)
	return mission, func() {
		cleanup()
	}, nil
}
